apiVersion: apps/v1
kind: Deployment
metadata:
  name: test01
spec:
  selector:
    matchLabels:
      app: test01
  template:
    metadata:
      labels:
        app: test01
    spec:
      nodeSelector:
        dtarget: worker
      containers:
      - name: test01-container
        image: quay.apps.ocp.komsco.co.kr/komsco/test01:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: quay-registry-secret
